config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }

  root 'tasks#index'
  get 'tasks/review'
  resources :tasks
  resources :tasks do
    post :update_row_order, on: :collection
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true
  include RankedModel
  ranks :order_number
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:update_order_position, :show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.where(completed: false).rank(:order_number).all
  end

  def review
    @tasks = Task.where(completed: true).rank(:order_number).all
  end
  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @last_task = Task.rank(:order_number).last
    @task = Task.create!(name: params[:task][:name], start_on: params[:task][:start_on],
        due_on: params[:task][:due_on], completed: params[:task][:completed],
        order_number:  @last_task.order_number + 1)
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    if @task.update(task_params)
      redirect_to root_path, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_row_order
    @task = Task.find(task_params[:id])
    @task.order_number_position = task_params[:order_number_position]
    @task.save

    render nothing: true # this is a POST action, updates sent via AJAX, no view rendered
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:id, :name, :start_on, :due_on, :completed, :order_number_position, :uid)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="form container">
  <%= form_for(@task) do |f| %>
    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div></br>
    <div class="field">
      <%= f.label :start_on %><br>
      <%= f.date_field :start_on %>
    </div></br>
    <div class="field">
      <%= f.label :due_on %><br>
      <%= f.date_field :due_on %>
    </div></br>
    <div class="field">
      <%= f.hidden_field :completed, value: false %>
    </div></br>
    <div class="actions">
      <button class="btn btn-success active" type="submit">Submit</button>
    </div>
    </br>
  <% end %>
</div>

app/views/tasks/_new_task.html.erb
<div class="form container">
  <%= form_for(@task, remote: true) do |f| %>
    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div></br>
    <div class="field">
      <%= f.label :start_on %><br>
      <%= f.date_field :start_on %>
    </div></br>
    <div class="field">
      <%= f.label :due_on %><br>
      <%= f.date_field :due_on %>
    </div></br>
    <div class="field">
      <%= f.hidden_field :completed, value: false %>
    </div></br>
    <div class="actions">
      <%= f.submit "submit" %>
    </div>
    </br>
  <% end %>
</div>

app/views/tasks/_task.html.erb
<tr data-item-id="<%= "#{task.id}" %>" class="item">
  <td id="name<%= task.id %>"><%= task.name %></td>
  <% if task.start_on != nil && task.due_on != nil %>
    <td id="start_on<%= task.id %>"><%= task.start_on.strftime("%B %e, %Y") %></td>
    <td id="due_on<%= task.id %>"><%= task.due_on.strftime("%B %e, %Y") %></td>
  <% else %>
    <td id="start_on<%= task.id %>"><%= task.start_on %></td>
    <td id="due_on<%= task.id %>"><%= task.due_on %></td>
  <% end %>
  <td id="completed<%= task.id %>">
    <%= form_for task, remote: true do |f| %>
      <%= f.check_box :completed, class: "complete-box" %>
    <% end %>
  </td>
  <td><%= link_to 'Edit', edit_task_path(task), class: "btn btn-info" %></td>
  <td><%= link_to 'Destroy', task, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/tasks/create.js.erb
$('#new-form-container').html("");
$('#sortable').append("<%= j(render @task) %>");

app/views/tasks/edit.html.erb
<div class="header">
  <h1 class="edit-list-title">Edit List Item</h1>
</div>
</br>
<%= render 'form' %>

<div class="bottom-links">
  <%= link_to 'Back', root_path, class: "btn btn-info" %>
</div>

app/views/tasks/index.html.erb
<div class="header">
  <h1 class="list-title">To-Do List</h1>
</div>
<br>
<div class="container">
  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Start on</th>
        <th>Due on</th>
        <th>Completed</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody id="sortable">
      <div id='all-tasks'><%= render @tasks %></div>
    </tbody>
  </table>
  <br>
</div>
<div id="new-form-container"></div>

<div class="bottom-links">
  <%= link_to 'New Task', new_task_path, remote: true, class: "btn btn-primary active" %>
  <%= link_to 'View Completed Tasks', tasks_review_path, class: "btn btn-primary active" %>
</div>

app/views/tasks/new.js.erb
$('#new-form-container').html("<%= j(render partial: 'new_task') %>");
$("#new-form-container").fadeIn();

app/views/tasks/review.html.erb
<h1 class="list-title">Completed Tasks</h1>
</br>
<div class="container">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Start on</th>
        <th>Due on</th>
        <th>Completed</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody id="sortable">
      <div id='all-tasks'><%= render @tasks %></div>
    </tbody>
  </table>
</div>
<br>
<div class="bottom-links">
  <%= link_to 'Back', root_path, class: "btn btn-primary active" %>
</div>

app/views/tasks/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Start on:</strong>
  <%= @task.start_on %>
</p>

<p>
  <strong>Due on:</strong>
  <%= @task.due_on %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<p>
  <strong>Order number:</strong>
  <%= @task.order_number %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>